#!/bin/sh

DEVICE="$(cat /opt/inkbox_device)"

if [ "${DEVICE}" == "n705" ]; then
	OLD_DPI=${QT_FONT_DPI}
	QT_FONT_DPI=170
else
	QT_FONT_DPI="$(cat /mnt/onboard/.adds/inkbox/.config/09-dpi/config 2>/dev/null)"
fi

LD_LIBRARY_PATH='/mnt/onboard/.adds/qt-linux-5.15.2-kobo/lib' LD_PRELOAD=/lib/invert_screen.so /mnt/onboard/.adds/inkbox/2048-bin

if [ "${DEVICE}" == "n705" ]; then
	QT_FONT_DPI=${OLD_DPI}
fi

LD_LIBRARY_PATH='/mnt/onboard/.adds/qt-linux-5.15.2-kobo/lib' QT_FONT_DPI=${QT_FONT_DPI} /mnt/onboard/.adds/inkbox/inkbox
