#!/bin/sh

calculate() {
        result=$(awk "BEGIN { print "$*" }")
        printf "%.0f\n" ${result}
}

DEVICE="$(cat /opt/inkbox_device)"

if [ "${DEVICE}" == "n705" ]; then
	FACTOR=0.55
elif [ "${DEVICE}" == "n873" ]; then
	FACTOR=0.79
else
	FACTOR=0.65
fi

QT_FONT_DPI="$(calculate $(cat /mnt/onboard/.adds/inkbox/.config/09-dpi/config 2>/dev/null)*${FACTOR})" LD_LIBRARY_PATH='/mnt/onboard/.adds/qt-linux-5.15.2-kobo/lib:/mnt/onboard/.adds/inkbox/system/lib' LD_PRELOAD=/lib/invert_screen.so /mnt/onboard/.adds/inkbox/qalculate-bin -stylesheet "/mnt/onboard/.adds/inkbox/system/share/stylesheets/qalculate.qss" -w "/mnt/onboard/.adds/inkbox/system/share/profiles/qalculate/default.ini"

LD_LIBRARY_PATH='/mnt/onboard/.adds/qt-linux-5.15.2-kobo/lib' QT_FONT_DPI="$(cat '/mnt/onboard/.adds/inkbox/.config/09-dpi/config' 2>/dev/null)" /mnt/onboard/.adds/inkbox/inkbox
